version: '3.8'

services:
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Load balancer port
      - "8081:8081"  # Admin API port
    depends_on:
      - backend1
      - backend2
      - backend3
    volumes:
      - ./conf:/app/conf
    command: --config /app/conf/docker.conf

  backend1:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8001:8080"
    command: --addr :8080 --id server1

  backend2:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8002:8080"
    command: --addr :8080 --id server2

  backend3:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8003:8080"
    command: --addr :8080 --id server3 