version: '3.8'

services:
  loadbalancer:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./backends/server1:/usr/share/nginx/html
    environment:
      - NGINX_PORT=80

  backend2:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./backends/server2:/usr/share/nginx/html
    environment:
      - NGINX_PORT=80

  backend3:
    image: nginx:alpine
    ports:
      - "8083:80"
    volumes:
      - ./backends/server3:/usr/share/nginx/html
    environment:
      - NGINX_PORT=80 